export {
  setAnalyticsUserProperties,
  trackAchievementUnlocked,
  trackActivityCompleted,
  trackAdWatched,
  trackDailyWheelSpin,
  trackError,
  trackLessonCompleted,
  trackLessonStarted,
  trackLevelUp,
  trackLogin,
  trackNovaEvolution,
  trackOfflineSync,
  trackProfileCreated,
  trackPurchase,
  trackQuestCompleted,
  trackScreenView,
  trackSignUp,
  trackStreakDays,
  trackSubscriptionEvent,
  trackXPGained,
} from './analyticsService';
